
[theme]
base = "light"

primaryColor = "#fcf003"
backgroundColor = "#fcba03"
secondaryBackgroundColor = "#966d03"
textColor = "#2e2102"
borderColor = "#6e5016"
linkColor = "#7FD1C1"
linkUnderline = true

codeBackgroundColor = "#0B0E14"
codeTextColor = "#0a0801"
dataframeBorderColor = "#2A3446"
dataframeHeaderBackgroundColor = "#1B2233"

font = "times new roman"
headingFont = "times new roman"
codeFont = "monospace"
baseFontSize = 16
baseFontWeight = 400
codeFontSize = "0.9rem"
codeFontWeight = 400

baseRadius = "full"
buttonRadius = "full"
showWidgetBorder = true
showSidebarBorder = true

metricValueFontSize = "2rem"
metricValueFontWeight = 600

chartCategoricalColors = ["#FFC93C", "#7FD1C1", "#E88873", "#8E9AF2", "#B8E1D9"]